"use client";

import React, { useState } from 'react'
import Image from 'next/image'
import { motion, AnimatePresence } from 'framer-motion';
import { useRouter } from 'next/navigation';
import ErrorModal from '@/components/ui/ErrorModal';
import Loading from '../home/components/loading';
import { ArrowLeft } from 'lucide-react';

export default function LoginPage() {
  const router = useRouter();
  const [form, setForm] = useState({ email: "", senha: "" });
  const [message, setMessage] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/auth/login`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(form),
      credentials: "include",
    });

    const data = await res.json();
    console.log(form);
    if (data.message === "Login realizado com sucesso") {
      router.push("/home");
    } else {
      setMessage(data.message);
    }
    console.log(data);
  };

  return (
    <>
      {message && (
        <ErrorModal message={message} onClose={() => setMessage(null)} />
      )}
      
      <AnimatePresence>
        <div className="w-full h-[100vh] flex justify-center bg-white">
          <motion.div 
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.98 }}
          className="w-[40px] h-[40px] absolute top-5 left-5 cursor-pointer ">
            <ArrowLeft onClick={() => router.push("/")} className='w-full h-full '/>
          </motion.div>
          <div className="logincontainer w-[1600px] py-5 m-auto max-w-[90%] mx-auto flex lg:flex-row flex-col justify-center items-center">
              <motion.div 
              key="loginimage"
              initial={{ opacity: 0, y: 10 }}
              animate={{opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: 10 }}
              transition={{ duration: 0.9, ease: "easeInOut", type: "spring", bounce: 0.4}}
              className="loginimage min-w-[50%] max-w-[50%] flex items-center h-fit">
                <Image
                  src="/loginimage.svg"
                  alt="Login Image"
                  width={500}
                  height={500}
                  priority
                  className='w-full '
                  placeholder="blur"
                  blurDataURL="data:image/png;base64,...." // generated by Next.js automatically if in /public
                />
              </motion.div>
            <motion.div key="login" className="login  w-[90%] lg:max-w-[50%] flex justify-center items-center">
              <div className=" flex flex-col w-[500px] gap-[20px] max-w-[100%] h-full ">
                <div className="">
                  <h1 className='entrar text-[30px] font-bold leading-none text-[#EB7262]'>Entrar</h1>
                  <h2 className='bemvindo text-[18px] '>Bem-vindo de volta! Pronto para mais um dia de aprendizado?</h2>
                </div>
                
                <form onSubmit={handleSubmit} className='flex flex-col gap-1 ' >
                  <div className="flex flex-col gap-4 items-end">
                    <input type="email" required placeholder='Digite seu email' onChange={(e) => setForm({ ...form, email: e.target.value })} className='p-3 w-full rounded-[25px] outline-[rgba(151,103,248,0.6)] text-[18px] border-2 border-[rgba(10,8,9,0.6)]'/>
                    <input type="password" required placeholder='Digite sua senha' onChange={(e) => setForm({ ...form, senha: e.target.value })} className='p-3 w-full rounded-[25px] outline-[rgba(151,103,248,0.6)] text-[18px] border-2 border-[rgba(10,8,9,0.6)]'/>
                    <a href='/esqueceu-senha' className=' text-[#3881AF] w-fit text-[15px] '>Esqueceu a senha?</a>
                  </div>

                  <motion.button 
                  whileTap={{scale: 0.99}}
                  whileHover={{scale: 1.01}}
                  transition={{ duration: 0.2, ease: "easeInOut"}}
                  type='submit' className='loginbotao bg-[#804EE5] py-[10px] text-white text-[18px] rounded-[25px] shadow-md'>Entrar</motion.button>

                </form>
                <h2 className='text-[15px] w-full text-center'>Não tem uma conta? <a href="/registrar" className='text-[#3881AF]'> Registre-se</a></h2>

              </div>
        
            </motion.div>
          </div>
        </div>
        
      </AnimatePresence>
    </>
  )
}

